### PR TITLE
bundle nt2 headers as well

### PR DESCRIPTION
**Pull request by kevinushey**
This PR:

- Adds a script that builds `nt2`, and copies over the generated headers -- this would hopefully be useful if we needed to rebuild `nt2` at a later date,
- Amends `RcppParallel` headers where appropriate,
- Adds a couple patches that clean up (bogus) compiler warnings in `nt2`.

@jjallaire, let's chat before we merge -- we should probably change the header to `RCPP_PARALLEL_USE_NT2`, and we may want to ask that users explicitly include the headers they want from `nt2`, rather than just throwing everything in, as compiling a simple file now takes ~20 seconds, with `clang` gobbling up nearly a gigabyte of RAM in the process. (And this is on a 2015 MBP, so people with older systems would suffer a lot)

I think we should also make sure we are prominently displaying that we are using `nt2`, and provide links back to the host repository when appropriate.

### CODE REVIEW

**Comment by kevinushey** [comment]
This may be also at the point where we should just split it into a separate package (`RcppNt2`) or something.

**Comment by eddelbuettel** [comment]
Wowser:  _Files changes: 9006_

**Comment by jjallaire** [comment]
We agreed to just create a new package (RcppNT2)

On Tue, Jan 26, 2016 at 3:51 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by kevinushey** [comment]
Closing this as we've now created a standalone package [RcppNT2](https://github.com/RcppCore/RcppNT2).

**Pull request closed without merging**
