### PR TITLE
prepare for release

### PR DESCRIPTION
**Pull request by kevinushey**

### CODE REVIEW

**Comment by kevinushey** [comment]
FYI @Enchufa2; I will unfortunately have to back out the TBB auto-detection for the upcoming RcppParallel release.

The current version of `rstan` / `StanHeaders` on CRAN tries to use some TBB APIs which have been removed from the most recent TBB release. Unfortunately, the CRAN machines have a system installation of this new version of TBB installed, which is hence not compatible with the version of `StanHeaders` currently on CRAN. Which means auto-detecting and using that copy of TBB causes RcppParallel to fail its reverse dependency checks.

You can still turn it on by setting the environment variable `TBB_AUTODETECT=TRUE` when installing RcppParallel, but for now we'll still default to using the older, bundled version.

**Comment by eddelbuettel** [comment]
For what it worth I always found @bgoodri to respond well and accomodate requests for updates; I usually have those from RcppEigen.  Stan being its own ecosystem these things tend to take a moment but it might be something to consider for the next release.

With that, thanks as always for looking after RcppParallel. It's a challenging package.

**Comment by bgoodri** [comment]
@kevinushey Which APIs are being used by Stan that no longer exist in TBB?

**Comment by kevinushey** [comment]
@bgoodri I created an issue here: https://github.com/stan-dev/rstan/issues/1041

As I understand it, TBB's task scheduler is now deprecated, and the newest release no longer includes the `tbb/task_scheduler_init.h` header, which is used in StanHeaders in `stan/math/prim/core/init_threadpool/tbb.hpp`.

**Pull request merged**
