### PR TITLE
Feature/vc simd support

### PR DESCRIPTION
**Pull request by kevinushey**
This PR represents the first steps in wrapping `Vc` as part of the RcppParallel package, but there's a lot left to go.

## TODO
- [ ] Handle requirement of CMake >= 3.0
- [ ] Handle different architectures / library path extensions.
- [ ] Make it possible to use `Vc` in `sourceCpp()` -- provide a plugin? Augment the RcppParallel depends?
- [ ] Examples, documentation, tests...

## Platform-specific tests
- [ ] Windows
- [ ] OS X
- [ ] Linux (Ubuntu, CentOS)

### CODE REVIEW

**Comment by jjallaire** [comment]
The build/linking requirements for Vc look pretty imposing. It also requires C++11 which we don't (yet) have on Windows and don't have on CentOS/RHEL. It looks to me like boost::simd is header only. Even if it's not quite as capable it might be much easier to integrate (we could possibly even add it to the BH package? @eddelbuettel?). Here is the link to boost::simd: https://github.com/NumScale/boost.simd

**Comment by jjallaire** [comment]
On second thought I think the right thing to do would be to:

1. Embed boost::simd in this package

2. Write higher level mappings/converters to RVector<T> and RMatrix<T>

3. Have this package depend on BH for whatever boost::simd needs from boost.

**Comment by eddelbuettel** [comment]
Agree with @jjallaire because simd site clearly states

> Portable SIMD computation library - To be proposed as a Boost library

so it isn't yet part of Boost.  Also note that if we wrap it we get implicit versioning dependencies in BH. Uwe told me about a BH package which embedded Boost Regex.  Tends to work for a few releases but eventually goes booom.

(And @kevinushey should probably be granted write permissions here ...)

**Comment by kevinushey** [comment]
I agree that we should pursue Boost.SIMD given the pains in handling Vc's dependency. I'll close this for now (we can revisit if we discover Boost.SIMD has its own surprising issues)

**Comment by kevinushey** [comment]
FWIW the following links are dead for me now:

https://github.com/NumScale/boost.simd
https://github.com/jfalcou/boost.simd

No idea why they're gone. :/ But there's still a version available in

https://github.com/jfalcou/nt2/tree/master/modules/boost/simd

Perhaps we'll try bundling that.

**Comment by jjallaire** [comment]
Maybe post an issue there asking why the standalone repos are gone?

**Comment by jfalcou** [comment]
as I answered, we're moving the repo someplace else as we need to clean up some stuff before introduction to Boost. 

I'm a bit busy atm but if you need helps setting up//using Boost.SIMD, just ping me on my email. I'll gladly help.

**Comment by kevinushey** [comment]
Thanks @jfalcou -- right now I'm proceeding by using the version of Boost.SIMD bundled with `nt2`, but I'll try also building the standalone version once that's available again.

Thanks for your awesome work here!

**Comment by eddelbuettel** [comment]
:+1: for pushing towards Boost inclusion

**Pull request closed without merging**
