### PR TITLE
Intel TBB 2018 Update 1

### PR DESCRIPTION
**Pull request by jolars**
This pull request updates TBB to [2018 Update 1](https://software.intel.com/en-us/articles/intel-threading-building-blocks-release-notes/).

It builds fine on windows locally, unbuntu on [travis-ci](https://travis-ci.org/jolars/RcppParallel/builds/283878991) and [macOSX on r-hub ](https://builder.r-hub.io/status/RcppParallel_2018.1.0.tar.gz-041ab5e14f98735d27c8b7c767d058ae).

The PR includes reverse dependency checks with one build error that I believe to be due to some issue with a source installation.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I am set-up here too for rev.dep checks if it helped but always sounds like @jolars is bloody thorough that that analysis is already baked in :)

**Comment by eddelbuettel** [comment]
Bump and poking @kevinushey ...

**Comment by kevinushey** [comment]
LGTM -- thanks for putting this together! I'll wait to see if @jjallaire has any comments we can merge after if all looks well.

**Comment by jjallaire** [comment]
LGTM as well.

**Pull request merged**
