### PR TITLE
request CXX11 standard for newer R, platforms

### PR DESCRIPTION
**Pull request by kevinushey**
Primarily to silence 'long long' warnings on CRAN.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Digging into one of the Travis logs I see

```
g++ -o tbb_main.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -mrtm  -fpic  -D__TBB_BUILD=1 -Wall   -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/tbb_main.cpp
make[2]: *** No rule to make target `concurrent_vector_v2.o', needed by `libtbb.so.2'.  Stop.
make[2]: Leaving directory `/home/travis/build/RcppCore/RcppParallel/RcppParallel.Rcheck/00_pkg_src/RcppParallel/src/tbb/build/lib_release'
make[1]: *** [tbb_release] Error 2
make[1]: Leaving directory `/home/travis/build/RcppCore/RcppParallel/RcppParallel.Rcheck/00_pkg_src/RcppParallel/src/tbb/src'
cp: cannot stat ‘tbb/build/lib_release/libtbb*.*’: No such file or directory
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
```

Any idea?

**Comment by kevinushey** [comment]
We normally try to define `-DTBB_NO_LEGACY=1`, but it seems like that wasn't making it way into the TBB compilation. I'm going to try to enforce that compiler definition a different way.

**Comment by kevinushey** [comment]
I am very confused. The command line invocation looks correct:

```
CONLY="gcc -std=gnu99" CPLUS="g++" PIC_KEY="-fpic" WARNING_SUPPRESS="" make -e stdver=c++0x CXXFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -DTBB_NO_LEGACY=1" tbb_release tbbmalloc_release tbb_build_prefix=lib
```

And yet, the compilation attempt doesn't pass on those CXXFLAGS (even though those _are_ passed on when I build locally):

```
g++ -o concurrent_hash_map.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -mrtm  -fpic  -D__TBB_BUILD=1 -Wall   -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_hash_map.cpp
```

Note the lack of `-DTBB_NO_LEGACY` (and other flags). It must be something idiosyncratic to Travis, but I have no idea what it might be.

**Comment by kevinushey** [comment]
This PR strips out off of the old / legacy stuff, thereby obviating the need to specify `-DTBB_NO_LEGACY`. Looks like Travis is happy enough with this approach, but I still wish I knew why things weren't working as expected before...

**Comment by eddelbuettel** [comment]
Could there be older clients that get upset for the lack of legacy, or does everybody take the default (current, non-legacy) API?

**Comment by kevinushey** [comment]
We've always built RcppParallel without the legacy client -- that is, this change is just a much more ham-fisted way of achieving `-DTBB_NO_LEGACY=1`, by just literally stripping out the legacy bits.

**Comment by kevinushey** [comment]
Closing this because it breaks things for reasons I was never able to get to the bottom of.

**Pull request closed without merging**
