### PR TITLE
Allow constructing RMatrix from a non-const buffer

### PR DESCRIPTION
**Pull request by galexv**

### CODE REVIEW

**Comment by galexv** [comment]
This is to address issue #139.

**Comment by kevinushey** [comment]
Thanks!

**Comment by jwood000** [comment]
I had the same issue, however my fix was to implement a similar pattern as the more common constructor:

https://github.com/RcppCore/RcppParallel/blob/cb514e8658458625a9f99eb7fa74157d20262a44/inst/include/RcppParallel/RMatrix.h#L199-L205

Thus, I implemented the following:

```c++
   inline RMatrix(const T* data, std::size_t nrow, std::size_t ncol) 
      : data_(const_cast<T*>(data)), nrow_(nrow), ncol_(ncol) 
   {
   }
```
 
I had experimented with the current fix (removing the `const` altogether), however I ended up using the fix above.

I'm not sure which is better, but my gut feeling is that the keeping `const T*` is better.

**Comment by galexv-test** [comment]
This is a possibility, but my gut feeling is just the opposite: i do not like `const_cast`s :slightly_smiling_face:, and for a reason.  IMHO, basically, the constructor above lies to me promising to create an object that cannot change my data (via the provided pointer).  For example, i could have passed a pointer to an array in some kind of read-only memory, and the compiler would not say a word, resulting in undefined behavior (UB) (see, e.g., https://stackoverflow.com/q/4042626).

Case in point: a simplified code at https://godbolt.org/z/WP5qes uses `const_cast<int*>` from a const-data pointer at line 30, then tries to assign to the pointed-to location (line 31), which results in a crash when compiled without optimization ("-O0"). Without the forced `const_cast` the corresponding piece of code (lines 17-18) produces a compilation error (as it should happen when a user tries to do something grossly incorrect). 

A side note: When the program is compiled with "-O1", the compiler deduces the result without actually running any memory access code, ignoring the incorrect assignment, so we get different results at different optimization levels, as is common when a UB is invoked.

**Comment by galexv** [comment]
This is a possibility, but my gut feeling is just the opposite: i do not like `const_cast`s :slightly_smiling_face:, and for a reason.  IMHO, basically, the constructor above lies to me promising to create an object that cannot change my data (via the provided pointer).  For example, i could have passed a pointer to an array in some kind of read-only memory, and the compiler would not say a word, resulting in undefined behavior (UB) (see, e.g., https://stackoverflow.com/q/4042626).

Case in point: a simplified code at https://godbolt.org/z/WP5qes uses `const_cast<int*>` from a const-data pointer at line 30, then tries to assign to the pointed-to location (line 31), which results in a crash when compiled without optimization ("-O0"). Without the forced `const_cast` the corresponding piece of code (lines 17-18) produces a compilation error (as it should happen when a user tries to do something grossly incorrect). 

A side note: When the program is compiled with "-O1", the compiler deduces the result without actually running any memory access code, ignoring the incorrect assignment, so we get different results at different optimization levels, as is common when a UB is invoked.

[Sorry for double posting, accidentally posted it from a temporary account :pensive: ]

**Pull request merged**
