### PR TITLE
README: example: Update to oneTBB 2021.2.0

### PR DESCRIPTION
**Pull request by hsbadr**
Use [the latest release of `oneTBB`](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.2.0) in the README example.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Is there a way to have a permanent link for 'current' oneTBB?

**Comment by hsbadr** [comment]
> Is there a way to have a permanent link for 'current' oneTBB?

@eddelbuettel Good point! On one hand, we can automatically get the last tag using something like:
```bash
TBB_RELEASE="https://api.github.com/repos/oneapi-src/oneTBB/releases/latest"
TBB_TAG=$(curl --silent $TBB_RELEASE | grep -Po '"tag_name": "\K.*?(?=")')
TBB_VERSION=${TBB_TAG#?}
```
On the other hand, we may want the users to explicitly select the TBB version they need, in case the latest version may cause issues for some of their packages.

What do you think?

**Comment by eddelbuettel** [comment]
Yup. It's complicated.  Other projects face that too and I don't what is best. I like how the boost.org website pivots me to latest releaes from old links, yet kills me each time when I try to chase the invariant link.

I think this can be argued well either way.  A _working_ fixed link has merit, a current one has too.   Maybe just show one (as in the update you proposed) and then show to auto-compute a newer one?   I just don't want to establish a pattern that we chase that here in PRs every few months which seems like ... marginally useful yet possibly a waste of everybody's time?

**Review by eddelbuettel — APPROVED** [review]
Nicely done.

**Comment by hsbadr** [comment]
@kevinushey Could you review/merge this PR?

**Comment by kevinushey** [comment]
Done! Sorry for missing this before.

**Pull request merged**
