### PR TITLE
Add support for TBB on Solaris

### PR DESCRIPTION
**Pull request by jjallaire**
Add Solaris to the whitelist of supported platforms for TBB. 

Note that this is not yet tested (because I don't have a working Solaris configuration) so should not be merged.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Do you think Martyn may be able to help?  He has Solaris with (IIRC) the gcc toolchain.  Maybe also SunPro -- slightly foggy memory.

**Comment by jjallaire** [comment]
Very well might be able to. I posted to Rcpp-devel with a general call for
help from anyone on the list who had the right configuration/expertise. Did
you see that message? (just making sure I posted to the list correctly as
no one has yet replied).

**Comment by eddelbuettel** [comment]
Hm, I did not see it yet at my end, and [gmane](http://news.gmane.org/gmane.comp.lang.r.rcpp) does not have it either,

In the past you seem to have posted as `jj.allaire@gmail.com` so it safe to assume that is good. Let me know what other ones you'd use and I whitelist those.

**Comment by jjallaire** [comment]
I also use jj@rstudio.com

I'll repost from jj.allaire@gmail.com

**Comment by jjallaire** [comment]
Just reposted. Let me know if you don't see it.

**Comment by eddelbuettel** [comment]
Saw it now, and followed up. Also white-listed jj AT rstudio DOT com.

**Pull request merged**
