### PR TITLE
add in boost.SIMD

### PR DESCRIPTION
**Pull request by kevinushey**
This PR will encompass the work to bundle + use + expose Boost.SIMD in RcppParallel.

## Building

Thus far, I've brought in by building + installing `nt2`, and then copying the `boost` headers required into this package. We can probably shrink this down by building Boost.SIMD standalone (once the repository is back online), and it would be good to have a script that we can use to update / pull a particular version of Boost.SIMD.

## Examples

Right now, we just have a simple bit of code that wraps the SIMD [hello world](http://nt2.metascale.fr/doc/html/tutorials/simd_hello_world.html). It works (yay!) so we're off to a very good start.

### CODE REVIEW

**Comment by kevinushey** [comment]
It looks like `Boost.SIMD` provides an `algorithm.hpp` header, which provides a STL-like interface over arbitrary ranges. Perhaps we should target that for any wrappers?

**Comment by eddelbuettel** [comment]
BH is at 1.60.0 at CRAN. Are you current?

**Comment by kevinushey** [comment]
I believe so, why? (The Travis build failed for some other strange reason)

**Comment by eddelbuettel** [comment]
JJ mentioned something about 1.58 earlier.

**Comment by kevinushey** [comment]
Testing with `simd::accumulate`, I get a 2x (!) automagic speedup in a 'sum' computation on my machine. Very nice to see!

**Comment by kevinushey** [comment]
@eddelbuettel, any idea what this error from Travis mean?

```sh
Creating config file /etc/R/Renviron with new version
/var/lib/dpkg/info/r-base-core.postinst: 57: /var/lib/dpkg/info/r-base-core.postinst: mktexlsr: not found
dpkg: error processing r-base-core (--configure):
 subprocess installed post-installation script returned error exit status 127
```

Was R updated recently? Does it depend on some new package, or something?

**Comment by jjallaire** [comment]
Yes definitely!

**Comment by eddelbuettel** [comment]
@kevinushey A bug in the postinst I introduced (and fixed).  We have to wait for Michael to provision this as 3.2.3-4.  Very sorry.

**Comment by eddelbuettel** [comment]
Can you sink with master?  I just told the `.travis.yml` about BH and switched to r-cran-* install for Rcpp too) -- see 34bc60852b393d487c73c6dd343f7543fde1b244

**Comment by eddelbuettel** [comment]
We had no LinkingTo: for BH.  I just added that.  Can you try again?

**Comment by eddelbuettel** [comment]
Ready to merge this, @jjallaire ?

**Comment by jjallaire** [comment]
We've discussed a few more refinements. Once those land I'll merge it.

On Thu, Jan 14, 2016 at 6:07 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Update BH beyond what the package has, or upgrade to current Boost 1.60.0 in currnt BH_1.60.0 ?

**Pull request merged**
