### PR TITLE
Enable support for TBB on windows

### PR DESCRIPTION
**Pull request by jjallaire**

### CODE REVIEW

**Comment by jjallaire** [comment]
When building on Windows I see the following linker warnings:

```
task.o: duplicate section `.rdata$_ZTIN3tbb4taskE[typeinfo for tbb::task]' has different size
arena.o: duplicate section `.rdata$_ZTIN3tbb4taskE[typeinfo for tbb::task]' has different size
scheduler.o: duplicate section `.rdata$_ZTIN3tbb4taskE[typeinfo for tbb::task]' has different size
```

@vdbg do you see that as well? Any idea what might be causing this?

**Comment by jjallaire** [comment]
Searched for the linker warning I am seeing and noted that someone else compiling with cygwin had the same issue: http://www.snip2code.com/Snippet/222317/TBB-Compile-Output

**Comment by vdbg** [comment]
This looks like a known MinGW bug (quite a few reports, many not for tbb). I'm getting the same warning for a regular MinGW (not rtools) build

I tried the various ideas/answers I found on StackOverflow and other, nothing worked.

**Comment by jjallaire** [comment]
That's what I gathered. I think we don't need to worry about it.

**Pull request merged**
